
SQLALCHEMY_DATABASE_URI = "sqlite:///quiz.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = "b3i45noi4n5ou43b5ou43n543n5u3"  
JWT_SECRET_KEY = "bb4j234v5yu43v5u4v5ihb5ih4b54"

JWT_TOKEN_LOCATION = ["headers", "cookies"]
JWT_COOKIE_SECURE = False  
JWT_ACCESS_COOKIE_PATH = "/"  
