name: CI/CD and Auto-Commit Database

on:
  push:
    branches:
      - main
  schedule:
    # Run at 15-minute intervals (adjust as needed)
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build-and-commit-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        # Replace this with your test command, if any
        run: |
          echo "Running tests..."
          # e.g., pytest --maxfail=1 --disable-warnings -q

      - name: Commit database changes
        env:
          # Provide a GitHub token (default provided by Actions) to push commits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git with a bot identity
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # Run our commit script (ensure commit_db.sh is executable)
          ./commit_db.sh
