name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Initialize / Migrate Database (creates/updates instance/quiz.db)
      - name: Initialize / Migrate Database
        run: |
          python -c "from app import app, init_db; init_db(app)"

      # 5. Run tests (if any exist)
      - name: Run tests
        run: |
          pytest || echo "No tests found, continuing..."
        continue-on-error: true

      # 6. Check for database changes and commit if needed
      - name: Check for DB changes and commit if needed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          if [ -n "$(git status --porcelain instance/quiz.db)" ]; then
            echo "Database file has changes. Committing..."
            git add instance/quiz.db
            git commit -m "Auto-update instance/quiz.db"
            git push
          else
            echo "No changes in instance/quiz.db."
          fi

      # 7. Trigger a deployment on Render using the API
      - name: Trigger Render Deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}"
